dist: bionic
language: java
jdk:
  - openjdk11
git:
  submodules: false
before_install:
  - rm ~/.m2/settings.xml || true
  - ulimit -c unlimited -S
cache:
  directories:
    - $HOME/.m2

env:
  - LOGGING_LEVEL="ERROR"

script: mvn clean verify -q
